version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-201-55-4.compute-1.amazonaws.com
            database: d26gr4r27eq3l0
            schema: public
            user: djlhffxekclcfq
            password: 9f912162543515d32ef4d69f32c4d9c0a2284a37e6e079ce9d8ecc012592500d
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true